name: Module Release
description: Create immutable GitHub Release with module validation
author: ylarod

branding:
  icon: package
  color: blue

inputs:
  file:
    description: Path to the module.zip file to upload
    required: true
  tag_name:
    description: Git tag name for the release
    required: false
  name:
    description: Release name (defaults to tag name)
    required: false
  body:
    description: Release body/description
    required: false
  body_path:
    description: Path to file containing release body
    required: false
  prerelease:
    description: Mark as prerelease
    required: false
    default: 'false'
  target_commitish:
    description: Commitish value for the tag
    required: false
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  generate_release_notes:
    description: Auto-generate release notes
    required: false
    default: 'false'
  make_latest:
    description: Mark as latest release (true/false/legacy)
    required: false

outputs:
  url:
    description: Release HTML URL
  id:
    description: Release ID
  upload_url:
    description: Release upload URL

runs:
  using: node24
  main: dist/index.js
